### ISSUE TITLE
Support for multiple embeds?

### ISSUE THREAD

**Issue by shutupflanders** [laracord/framework#125]
Thanks for this package, it's really streamlined my bot development.
Is there a possibility we could add support for multiple embeds in a single message? I've read through the docs and code and it seems there's only support for a single embed at the current time (unless I'm missing something)

Happy to have a go myself but you guys know the framework better than I do!

Thanks again

**Comment by Log1x** [comment]
Sorry for the delay! I've added support for this in v2.5. I need to add docs but it looks something like this:

```php
$embed = $this
    ->message()
    ->title('Hello world');

return $this
    ->message()
    ->withEmbeds([
        $embed->content('1')->build(),
        $embed->content('2')->build(),
        $embed->content('3')->build(),
    ])
    ->reply($message);
```
