### ISSUE TITLE
🧑‍💻 Request for Channel Webhook Integration

### ISSUE THREAD

**Issue by marky291** [laracord/framework#52]
We would like to request the implementation of a webhook integration feature that leverages the existing channel->webhooks() functionality provided by DiscordPHP. This integration is sought to enhance our application's connectivity and streamline our notification processes.

**Comment by Log1x** [comment]
Hi! I moved this to the framework repo.

Can you give me a better example of how this would be used? I'm struggling to understand the purpose or how I could provide better DX for it.

**Comment by marky291** [comment]
Hey! Sorry, it looks like it is the only way to dynamically set the bot name when sending messages. This is really useful for when you want the bot to change name (AI Characters) or for when you want to create chat between applications by using the logged in users name.

**Comment by Log1x** [comment]
Ideally we'd implement something like `->toWebhook($url)` in https://github.com/laracord/framework/blob/main/src/Discord/Message.php to start. 

I'd like to explore Webhook creation itself at a later date/in a separate issue.

**Comment by Log1x** [comment]
#73 proposes a solution to this. I ended up adding the webhook creation as it made sense in this case.

With the PR, your code would be reduced to something like:

```php
if ($messageCache->isEmpty()) {
    return;
}

$messageItem = $messageCache->pop();

$this
    ->message()
    ->username($messageItem->getUsername())
    ->body($messageItem->getMessage())
    ->webhook()
    ->send($messageItem->getChannelId());
```
