### ISSUE TITLE
Add "inline" parameter to fields() function

### ISSUE THREAD

**Issue by yonex68** [laracord/framework#75]
It's currently not possible to add the "inline" parameter for a group of fields:

![image](https://github.com/laracord/framework/assets/47473615/65c11d54-cef2-496c-a043-9b0d6e65cc25)

Here is my update in the `src/Discord/Message.php` file:

```
/**
 * Set the message fields.
 */
public function fields(array $fields, bool $inline = true): self
{
    foreach ($fields as $key => $value) {
        $this->field($key, $value, $inline);
    }

    return $this;
}
```

It prevents a bad format when you want that each field of your array displays on a new line.

Can you implement it on the next release? @Log1x 
Or do you want me to create a pull request from my fork?

**Comment by Log1x** [comment]
good idea! do you want me to do it now or do you want to do a PR?

**Comment by yonex68** [comment]
Thx :) Well as it took me 2min, feel free to implement it yourself ;)

**Comment by Log1x** [comment]
pushed a release
